GET http://localhost:8082/currencies
###
GET http://localhost:8082/currencies/inr
###
GET http://localhost:8082/currencies?min_value=0.01
###
GET http://localhost:8082/users
# Authorization: LetMeIn
###
GET http://localhost:8082/users/6607d086-7159-4c26-beb1-280c9f9cbf35
Authorization: LetMeIn
###
GET http://localhost:8082/users/search?gender=female
Authorization: LetMeIn
###
POST http://localhost:8082/blogs
Content-Type: application/json

{
    "title": "Travel blog on Bristol",
    "authors": [{
        "fullName": "Trossard",
        "email": "trossard@bristol.com",
        "image": "https://abcd.com/trossard.png"
    }]
}
###
GET http://localhost:8082/blogs
###
GET http://localhost:8082/blogs/669017993e9db89244a60992
###
DELETE http://localhost:8082/blogs/6692b92916bdf7b645ae98fb

###
PATCH http://localhost:8082/blogs/669017993e9db89244a60992
Content-Type: application/json

{
    "authors": [
        {
            "fullName": "Alan Shearer",
            "email": "alan@newcastle.com"
        }
    ]
}
###
GET http://localhost:8082/blogs/search?title=blog&author=kdb%40bestinprem.com
###
GET http://localhost:8082/blogs/search?title=blog
###
GET http://localhost:8082/blogs/search?author=kdb%40bestinprem.com
###
GET http://localhost:8082/blogs/search